---
title: "Debug"
author: "Red Tortoise, LLC"
date: "October 6, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r functionDefinitions, echo=FALSE, message=FALSE, warning=FALSE, comment="", tidy=TRUE}
investor.create <-function (value.taxable,
                            value.deferred,
                            value.exempt,
                            horizon = 10,
                            taxrate.state = 0,
                            taxrate.ordinc = 0,
                            taxrate.LTCG = 0,
                            taxrate.STCG = 0,
                            taxrate.qualdiv = 0,
                            taxrate.surcharge = 0.038,
                            income = NULL){
    investor.values <- c(taxed = value.taxable,
                         deferred = value.deferred,
                         exempt = value.exempt)
    taxrates <- c(OrdInc = (taxrate.ordinc + taxrate.state + taxrate.surcharge) * 
                           (1 - taxrate.state),
                  LTCG = (taxrate.LTCG + taxrate.state + taxrate.surcharge) * 
                         (1 - taxrate.state),
                  STCG = (taxrate.STCG + taxrate.state + taxrate.surcharge) *
                         (1 - taxrate.state),
                  QualDiv = (taxrate.qualdiv + taxrate.state + taxrate.surcharge) * 
                         (1 - taxrate.state),
                  taxRState = taxrate.state)
    temp <- value.deferred * (1 - taxrates["OrdInc"])
    names(temp) <- ""
    investor.values.at <- c(taxed.at = value.taxable,
                            deferred.at = temp,
                            exempt.at = value.exempt)
                            investor <- c(investor.values, investor.values.at, taxrates,
                            horizon = horizon)
    class(investor) <- "investor"
    return(investor)
    }

print.investor <- function (x, ...) {
    av <- data.frame(Account = c("Taxable", "Deferred", "Exempt", 
        "Total"), PreTaxValue = c(x["taxed"], x["deferred"], 
        x["exempt"], x["taxed"] + x["deferred"] + x["exempt"]), 
        AfterTaxValue = c(x["taxed.at"], x["deferred.at"], x["exempt.at"], 
            x["taxed.at"] + x["deferred.at"] + x["exempt.at"]))
    tax <- data.frame(Tax = unlist(strsplit("Ordinary Income, LT Cap Gain, ST Cap Gain, Qual Div, State", 
        split = ",")), Rate = c(x["OrdInc"], x["LTCG"], x["STCG"], 
        x["QualDiv"], x["taxRState"]))
    rownames(tax) <- NULL
    av$Account <- format(av$Account, justify = "left")
    av$PreTaxValue <- prettyNum(round(av$PreTaxValue, 0), big.mark = ",")
    av$AfterTaxValue <- prettyNum(round(av$AfterTaxValue, 0), 
        big.mark = ",")
    tax$Tax <- format(tax$Tax, justify = "left")
    tax$Rate <- prettyNum(tax$Rate * 100, format = "f", digits = 4, 
        nsmall = 2)
    print(av, row.names = FALSE)
    cat("\n")
    print(tax, row.names = FALSE)
    cat("\n")
    cat(paste("Time horizon is ", x["horizon"], "years."))
    cat("\n")
}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, comment="", tidy=TRUE}
library(knitr)
library(markdown)
library(rmarkdown)
library(readxl)
control<-read_xlsx("Control.xlsx")
control.data<-control[1,]
investor<-investor.create(value.taxable=control.data$Value.Taxable,
                          value.deferred=control.data$Value.Deferred,
                          value.exempt=control.data$Value.Exempt,
                          horizon=control.data$Horizon,
                          taxrate.state=control.data$TaxRate.State,
                          taxrate.ordinc = control.data$TaxRate.OrdInc,
                          taxrate.LTCG = control.data$TaxRate.LTCG,
                          taxrate.STCG=control.data$TaxRate.STCG,
                          taxrate.qualdiv = control.data$TaxRate.QualDiv,
                          taxrate.surcharge = control.data$TaxRate.Surcharge)
print(investor)
```

